import { Metadata } from 'next';
import React from 'react'
export const metadata: Metadata = {
  title: "user",
  description: "Generated by create next app",
};
export default function Users() {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa necessitatibus dolorem quas iste porro velit distinctio fugiat. Explicabo dolore vel at ducimus, id possimus quas voluptates eos. Repellat, consequuntur voluptates?</p>
    </div>
  )
}
