import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  Link  from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
     <div className="flex">
     <nav className="  h-[100vh] sticky top-0 text-right bg-gray-400 ">
        <div className="w-[250px]">
          <p className="p-4 hover:bg-white"> <Link className="text-[30px]  no-underline" href='/'>Home</Link></p>
          <p className="p-4 hover:bg-white"> <Link className="text-[30px]  no-underline" href='/counter'>counter</Link></p>
          <p className="p-4 hover:bg-white"> <Link className="text-[30px]  no-underline" href='/users'>users</Link></p>
        </div>
      </nav>
      <div>{children} </div>
     </div>
        </body>
    </html>
  );/*  */
}
